apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "TriZetto-Healthcare-App"
  appid: TriZetto-Healthcare-App
  description: |
   HealthCare
  links:
    - title: Documentation
      url: https://backstage.io/docs
    - title: Backstage Website
      url: https://backstage.io/
    - title: Blackduck Website
      url: https://github.com/deepan10/backstage-plugin-blackduck  
  annotations:
    github.com/project-slug: Auerbach, Brian/tps-app-file-manager
    flowsource/github-repo-owner: Auerbach, Brian
    flowsource/github-repo-name: tps-app-file-manager
    flowsource/azure-devops-project-key:  TPS
    backstage.io/techdocs-ref: url:
 
  tags:
    - payment
    - transcation
spec:
  type: service
  system: flowsource-demo
  owner: group:default-group
  lifecycle: Development
  providesApis:
    - Trizetto-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: TriZetto-API
  description: Retrieve API details
spec:
  type: openapi
  lifecycle: production
  owner: TriZetto-relations-team
  system: Trizetto-engagement-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Client Target API
    paths:
      /data:
        get:
          summary: Fetch client data
          responses:
            '200':
              description: Success
