apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Online-Payment-App"
  appid: online-payment-app
  description: |
    The customer authorises payment via an online form allowing the business to automatically collect the funds when due. The business' bank and the customer's bank communicate and action the payment request when the payment is due, ensuring the correct amount is debited from the customer and credited to the business.
  links:
    - title: Documentation
      url: https://backstage.io/docs
    - title: Backstage Website
      url: https://backstage.io/
    - title: Blackduck Website
      url: https://github.com/deepan10/backstage-plugin-blackduck  
  annotations:
    github.com/project-slug: ShreyasiGhoshCog/Test_repo
    flowsource/github-workflows: TicketBooking-Pipeline1
    flowsource/durationInDays: '180'
    flowsource/github-repo-owner: ShreyasiGhoshCog
    flowsource/github-repo-name: Test_repo,trizetto_reo_test
    flowsource/azure-devops-project-key: SPE - Flowsource-Implementation
    backstage.io/techdocs-ref: dir:.
    # cognizant/checkmarx-project-id: CAC_automationenginewindows_v4.3.1-latest
    # flowsource/sonarqube-project-key: 
    # flowsource/azure-pipelines: Infra_Automation
    # flowsource/azure-project-name: SPE - Flowsource-Implementation
    # flowsource/azure-repo-name: shreyasi_internal_repo_poc


    
    flowsource/dora-cicd-tool: jenkins
    flowsource/dora-scm-tool: github
    flowsource/dora-alm-tool: jira
    flowsource/dora-itsm-tool: service-now
    flowsource/dora-observability-platform: datadog
    flowsource/servicenow-configuration-item: ANNIE-IBM

    # NEW: This is where your CI sys_id goes
    # servicenow.com/incident-table: "incident"
    # servicenow.com/incident-filter: "cmdb_ci=b4fd7c8437201000deeabfc8bcbe5dc1"


    
    flowsource/jenkins-pipelines: demo,demo-failure
    flowsource/jenkins-pipelines-trigger: demo,demo-failure
    # flowsource/checkmarx-project-id: dummy

    flowsource/playwright-report-filename: XML_Report_GLO_DE_Complete.json
    flowsource/playwright-report-path: "playwright_flowsource/"
    flowsource/playwright-cloud-provider: AZURE
    # flowsource/veracode-app-name: dummy
    # blackduck/project: automation-center-messageinterface/ver.1
    # flowsource/fis-aws-region: us-east-2
    # flowsource/aws-resiliencehub-appname: demotest
    # flowsource/aws-resiliencehub-region: us-east-2
    # backstage.io/kubernetes-id: flowsource
    # backstage.io/kubernetes-namespace: flwdemo
    # endoflife.date/products: nodejs@18,react@17,python,kubernetes,postgresql
  tags:
    - payment
    - transcation
spec:
  type: service
  system: flowsource-demo
  owner: group:default-group
  lifecycle: Development
  providesApis:
    - spe-api
#   dependsOn:
#     - component:default/Payment-App-Gateway-System
#     - resource:default/Payment-App-User-Database1
#   providesApis:
#     - Payment-App-Gateway-System
# ---
# apiVersion: backstage.io/v1alpha1
# kind: Resource
# metadata:
#   name: Payment-App-User-Database1
#   description: Database for storing the details
#   annotations:
#     backstage.io/techdocs-ref: dir:.
# spec:
#   type: database
#   owner: group:default-group
#   system: flowsource-demo
# ---
# apiVersion: backstage.io/v1alpha1
# kind: API
# metadata:
#   name: Payment-App-Gateway-System
#   description: The repository contains the BSPlugins integrating the diffrent channels (Web, Skype for business, Cortana, WebEx Teams, MS Teams*, Twilio* & Custom Channels) into HiveCenter Chatops Engine. The interface provides single endpoint for tapping into the features offered part of the I&O automation platform.
#   tags:
#     - node
# spec:
#   type: openapi
#   lifecycle: Development
#   owner: group:default-group
#   system: flowsource-demo
#   definition:
#     $text: './api-info.yaml'


---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spe-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Client Target API
    paths:
      /data:
        get:
          summary: Fetch client data
          responses:
            '200':
              description: Success
