apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "TriZetto-Healthcare-App"
  appid: TriZetto-Healthcare-App
  description: |
   HealthCare
  links:
    - title: Documentation
      url: https://backstage.io/docs
    - title: Backstage Website
      url: https://backstage.io/
    - title: Blackduck Website
      url: https://github.com/deepan10/backstage-plugin-blackduck  
  annotations:
    github.com/project-slug: ShreyasiGhoshCog/Test_repo
    flowsource/github-repo-owner: ShreyasiGhoshCog
    flowsource/github-repo-name: trizetto_reo_test
    flowsource/azure-devops-project-key: SPE - Flowsource-Implementation
    backstage.io/techdocs-ref: url:https://github.com/ShreyasiGhoshCog/trizetto_reo_test/tree/main
 
  tags:
    - payment
    - transcation
spec:
  type: service
  system: flowsource-demo
  owner: group:default-group
  lifecycle: Development
  providesApis:
    - spe-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spe-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Client Target API
    paths:
      /data:
        get:
          summary: Fetch client data
          responses:
            '200':
              description: Success
